### ISSUE TITLE
Migrate from Picasso to Glide

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#1082]
So I noticed that some images are way more blurry than they should be and I tried to play around with Picasso to make them sharper to no avail (both Picasso 2.5.2 and 2.71828). I tried Glide and the result was much better. See the attached images for comparision.
My suggestion is we migrate our image loading to Glide because A) better quality and B) Glide also supports gifs (#961 #108)

my Avatar, loaded with Picasso:
![picasso](https://user-images.githubusercontent.com/10157047/53441388-0ab00280-3a07-11e9-96f7-b63b1bf4bef5.png)

my avatar, loaded with Glide:
![glide](https://user-images.githubusercontent.com/10157047/53441387-0ab00280-3a07-11e9-93b1-de337aa2c2fd.png)

**Comment by charlag** [comment]
It may be a good idea, but let's first check some things, because Glide is... big.
Do we use custom transformation to make avatars rounded? If so, the problem is likely there
Do we use `fit()` or something like that? It can use downsampling with all the consequences.
I checked both and it seems like...we just tell to download it

```java
            Picasso.with(avatar.getContext())
                    .load(url)
                    .placeholder(R.drawable.avatar_default)
                    .into(avatar);
```

Maybe we *should* try calling `fit()` there. It can be Android resizing images in a weird way.
I checked and I don't experience it so only you can check it.

Glide makes sense for other reasons (you can save configurations and use them afaik) but I would check this first anyway.

**Comment by connyduck** [comment]
Ok yes, its better with `fit()`, but not on a level with Glide
![picasso-fit](https://user-images.githubusercontent.com/10157047/53442686-28cb3200-3a0a-11e9-88bd-3f0ed240673d.png)

How can we add gif support if we stay with Picasso?

**Comment by charlag** [comment]
Ouch, that's still looking bad and I have no idea why, really
I'm not sure about gifs. I think Glide implements custom Drawable for that (and so does Fresco but for other reasons) so we could use something similar.
Probably it's just easier to migrate to Glide. It's made by Google Photos team I think and it is actively developed.

**Comment by charlag** [comment]
>Round Pictures: CircleImageView/CircularImageView/RoundedImageView are known to have issues with TransitionDrawable (.crossFade() with .thumbnail() or .placeholder()) and animated GIFs, use a BitmapTransformation (.circleCrop() will be available in v4) or .dontAnimate() to fix the issue.

**Comment by connyduck** [comment]
#1175
