### ISSUE TITLE
Darker avatars on post interactions look out of place on light theme

### ISSUE THREAD

**Issue by jhaye** [tuskyapp/Tusky#1258]
When others interact with my posts by favouring or boosting them, Tusky shows this in the 'Notifications' column. The avatars of the accounts involved get darkened currently, which looks great on dark themes, but really out of place on the light theme.

It would be great if this could be adjusted. Just making avatars lighter, instead of darker, might do the trick.

* * * *
- Tusky Version: 6.1

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Awesome idea, thx

**Comment by ShadowJonathan** [comment]
Having this same issue, most places in the app (borders, names, buttons, edges, avatars) seem to be more optimised for dark themes, maybe making those a little greyer would help with that?

**Comment by nikclayton** [comment]
https://toot.cat/@rnd/109542123623319383 is another report of this.

**Comment by nikclayton** [comment]
Looking at my in-app notifications in light mode I think this might only affect those that have an inset avatar.

<img width="50%" src="https://user-images.githubusercontent.com/773100/209444892-9e8ccb62-4c8a-4f27-a9cf-001e7271b587.png">

Hmm, actually, there's the same darkening of avatars with an inset in dark mode as well. That's odd.

**Comment by nikclayton** [comment]
It's because of this code : https://github.com/tuskyapp/Tusky/blame/6b957904570fe41e6c88fcac54561b542b4d7ad1/app/src/main/java/com/keylesspalace/tusky/adapter/NotificationsAdapter.java#L449 

@charlag : This was your change in https://github.com/tuskyapp/Tusky/commit/240fb372ba723c75495b77c579cc2a42f8525c93. Do you recall why?

Avatar's that are set elsewhere do not do this (e.g., https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java#L275).

Is it possible that the darkening was originally added to match Glide's buggy behaviour referenced in the comment on https://github.com/tuskyapp/Tusky/blob/develop/app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java#L287? That comment works around the problem, but maybe avatars in notifications were never updated to match?

**Comment by charlag** [comment]
I am not sure anymore. We've tried to match mastodon web but probably didn't quite do it right. What is the alternative, alpha?

**Comment by nikclayton** [comment]
Closing, this was fixed with https://github.com/tuskyapp/Tusky/pull/3159
