### ISSUE TITLE
"Gaslight nazis" mode, for nazi instances

### ISSUE THREAD

**Issue by SoniEx2** [tuskyapp/Tusky#1305]
Heya! I'd like to see Tusky add a "gaslight nazis" mode, a ML-based mode where all toots are replaced with pro-human-rights messages and can't be boosted or liked (because you don't know what the original toot said). This would be a good alternative to redirecting gab users to another website. It would generate posts like:

"Trans rights!"

"Queer trans POC are good! <3"

"I love my gay parents! ! !"

(etc)

and deterministically replace the posts' contents with one of these messages. note that the original sender details would still be kept.

Thank you <3

* * * *
- Tusky Version:
- Android Version:
- Android Device:
- Mastodon instance (if applicable):

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by BNolet** [comment]
I don't mean to be pedantic but I think that it would be important to include non-LGBTQ type messages as well.

**Comment by SoniEx2** [comment]
I can't edit github issues but these are good too:

"POC are valid!!!"

"autistic ppl are valid!!!"

"dsylexia is valid!!!!"

"I love my headmates <3"

"my muslim parents love me, their autistic daughter!"

and yes it'd be 100% important to include these!

**Comment by BNolet** [comment]
These are fantastic suggestions as well and I'd like to add some that would
also apply to those not in a marginalized groups:

"You're pretty cool!"

"Take care of yourself today so you can be the best you can be tomorrow"

"Don't be so hard on yourself, you're trying your best"

"Whatever it was, don't take it personally. They probably had a bad day"

**Comment by SoniEx2** [comment]
those are directed at the user, tho. they aren't anti-nazi enough.

**Comment by ealgase** [comment]
This seems pointless.  Why not just look at @selfcare@botsin.space's profile?

**Comment by ealgase** [comment]
And given this:
> those are directed at the user, tho. they aren't anti-nazi enough.
It seems that you care less about actually making the user happy, and more about having the app display political messages you agree with.

**Comment by BNolet** [comment]
The feature is for the user...no?

**Comment by SoniEx2** [comment]
yes, but what's the point if it doesn't benefit all users?

**Comment by raingloom** [comment]
This is not a terrible idea to be honest, at least in spirit. Social media can be exhausting for many so it would be very much "user friendly" to do something like this.

But there might be other ways to do it that could be worth exploring.

**Comment by raingloom** [comment]
IMHO it doesn't have to be... overtly anti nazi? Not if it's aggressively positive towards things the fash hate.

So the more general self care messages would be a good start but mixing them with expressly pro-diversity messages is even better.

**Comment by BNolet** [comment]
I'd argue that the suggestions I posted would benefit a larger amount of users including those targeted by your suggestions, @SoniEx2

**Comment by noirscape** [comment]
I'd say the issue would be out of scope for the application but I am not a maintainer.

Perphaps browse r/eyebleach or a similar sub if you're feeling moody.

**Comment by ealgase** [comment]
> I'd say the issue would be out of scope for the application but I am not a maintainer.
> 
> Perphaps browse r/eyebleach or a similar sub if you're feeling moody.

Yeah, this is really a weird request.  Fake political messages that you agree with is not a "feature", it's bloat.

**Comment by raingloom** [comment]
I'd ask why you'd think they are fake, but I can guess. It might be worth asking yourself if bloat is really what you're opposing.

**Comment by BNolet** [comment]
Fake as in these "toots" are not made by real people. They are not attached
to a person's identity but to the software.

They're not saying the political ideology is fake.

**Comment by PubliqPhirm** [comment]
The comment earlier in the thread of "they're not anti-Nazi enough" in response to other generic feel-good replacement posts implies a lack of good faith in this request.  Seems to be more so someone with an ax to grind rather than a being open to improvements on the original (good) idea.

That said, I do support the addition of a "feel-good" mode for when you've used way too much social media.

**Comment by raingloom** [comment]
I still think the word "fake" is not.... entirely apt in this case.

If we have fewer degrees of separation from the implementer(s) and instead of machine learning it's either a pre-selected phrases or a simple sentence structure based generator, I think we can call that genuine.

I'd opt for the latter, I think it would even be more personal, or at least more specific. To illustrate:

> Everyone deserves human rights.

Ok, a true statement, but a bit dry, a bit too general.

> X deserve human rights.

Where the X is substituted for something reminds you of individual groups that you would not have thought of. Examples for X include: "people of color", "trans people", "black people", "immigrants", "Muslims", "Christians".

**Comment by raingloom** [comment]
Implementing it in Tusky itself may not be the absolute perfect solution, but if someone is willing to do it, I think it's worth testing the idea.

The mode is not forced to be on, so it's not like suddenly everyone would be bombarded with it.

**Comment by charlag** [comment]
Hi everyone
I don't have too many spoons to clear my point but I think it doesn't have to be implemented as part of the Tusky.
If it would be a bot or even a fake server to which you switch when you need support it could work with any client. That's why we have client-server separation: many clients can reuse the same server logic/resources.

I'm not even talking about feasibility of implementing such a thing. None of the regular contributors have any substantial experience with ML and doing it on mobile is not an easy thing. Fixed set of phrases wouldn't have much effect. But again, we should think if it really belongs to the app first and I'm not sure yet. I like the idea of such a bot or maybe of hiding counters/notifications with settings (like [Pinafore](https://github.com/nolanlawson/pinafore/releases/tag/v1.9.0) did).

**Comment by SoniEx2** [comment]
it could be forced-on for certain instances, for sure. but it should be part of tusky so it can use ppl's avatars and names.

**Comment by charlag** [comment]
Oh no, I don't like deception, this doesn't feel right to me.

**Comment by SoniEx2** [comment]
it's not deception it's just a silly thing.

well, except on nazi-adjacent instances. then it's no longer a silly thing, or deception for that matter. then it's just a tool we can use against them.

**Comment by SoniEx2** [comment]
helpful context, maybe: https://ncase.me/crowds/

(the nazis already know this. how do you think they made fake news profitable.)

**Comment by BNolet** [comment]
I apologize for the length and I want it to be known that I do not intend to harm, nor insult, nor belittle anyone's struggles or experience. I simply don't believe that one should hijack someone else's platform and use it for something that is not its intended purpose.

@SoniEx2 Forcing your political ideology down someone's throat is not something I would take lightly, no matter how much I agree with the message behind it. 

You're bordering on the line of propagandizing a perfectly fine app for your own political gain. I believe that you're acting in bad faith in the name of good people (the people you purport to be supporting) and attempting to assimilate someone else's platform. 

If you have a political message to share, please do so on your own platform, don't try to take someone else's.

I agree that being anti-nazi is an important thing but I think that an anti-nazi mode is not "friendly" in the sense that you're just reminding yourself of the politically charged environment that surrounds many already. If the idea is to create a mode in Tusky where you can relax and "feel good" then using an "anti-nazi" feature will not achieve that if it's only targeted at those who are marginalized. 

I'm pretty sure that most trans people just want to be known as "normal" and not have to go on and on about the difficulties (or be reminded of them), I'm sure that Autistic individuals prefer to be thought of as "just like everyone else." No, you shouldn't hide who you are, but making it your only identity will only lead to othering and isolation in a world where the majority of people don't understand the struggles or might not be aware of them. 

You can say you don't want to associate with someone like that, but the truth is you'd be segregating yourself from the world. 

I think that this type of thing could be better implemented as a bot on a given instance (botsin.space for example) rather than a feature on an app that many people inside _and_ outside your circles use. This will not solve the problem of the nazi ideology existing in the minds of certain individuals. This will lead to _more_ political charge being brought forth.

**Comment by noirscape** [comment]
I feel like I oughta elaborate a little bit on my previous statement.

Specifically when I define the requirement for a "feel good" mode as defined in the original issue to be out of scope, I look at the idea of what Tusky is and what it is meant to be used for. Specifically, Tusky is meant to be a social media application, specifically one that interacts with Fediverse instances (main one being Mastodon, although I'll gladly commend the devs for their support with Pleroma instances.)

As a result, it is meant to be a mobile client that interacts with an instance on the fediverse. Rewriting incoming statuses to me seems more like the duty of the instance you specifically are on and something that should be handled by this instance (Pleroma provides this sort of feature already technically speaking with it's MRF). Editing the content of incoming statuses, whether enabled or not will cause confusion as to the actual statuses content and I don't believe that should be the duty of the Tusky application.

I do think that a "relaxed" mode in which the application hides anything that might cause what I for the lack of a better expression will call "social status feedback looping" would be useful.

**Comment by tobypinder** [comment]
While this mode as stated feels out of scope for a client like Tusky, perhaps it makes sense in the form of some kind of "display only messages from $federated_hosts" feature that could be combined with a bot driven instance to the same effect.

Such feature would be more flexible and generic without the thorny issue of generating/rewriting content.

**Comment by SoniEx2** [comment]
@charlag there, fixed.

**Comment by Laurelai** [comment]
I think this would be funny. I dont think they would do it. But it would be funny.

**Comment by noirscape** [comment]
That sounds like something severely out of scope and a much bigger waste of time 
to spend dev time on than just rickrolling them.

**Comment by ealgase** [comment]
An app should never gaslight users, no matter how bad those users are.  There are better ways to combat fascists.

**Comment by SoniEx2** [comment]
gaslighting is the online equivalent of hitting someone on the head with an aluminium bat.

**Comment by charlag** [comment]
Someone can use it to make fake screenshots and I don't like it.


9 Jul 2019, 20:54 by notifications@github.com:

**Comment by ealgase** [comment]
I'm not going to argue with someone who's actually defending gaslighting.  Ask actual victims of gaslighting, you shouldn't subject anyone to that.

**Comment by SoniEx2** [comment]
ask victims of punching if they like being punched.

yet we do punch nazis.

**Comment by SoniEx2** [comment]
(besides, as if you'd even listen to victims of gaslighting...)

**Comment by ealgase** [comment]
There are reasonable reasons to punch people.  There's never a good reason to gaslight someone.

**Comment by SoniEx2** [comment]
@charlag fake screenshots of nazis being good ppl? yeah, probably. I believe that'd just further speed up their demise, tho, even tho that's not part of the original goal.

**Comment by connyduck** [comment]
Please stop this discussion, there will not be such a feature in Tusky. Nazis need to be blocked, but we won't let them waste our time by spending more time on this than necessary.
