### ISSUE TITLE
Ban fascist and lolicon instances as well (not only a single free speech zone)

### ISSUE THREAD

**Issue by RockyTV** [tuskyapp/Tusky#1328]
Now that a feature to block select instances (thus not allowing users from these instances to login and use the app) was recently merged, why not extend the block to, for example, the toot.cafe blocklist?

https://toot.cafe/about/more#blocked-instances

And please, I don't want to hear anymore about the political discussion that's going on around the fediverse. I just want a reasonable response from the developers (or users themselves) regarding my suggestion, because I am a Tusky user concerned about its future after PR #1303 was merged.

**Comment by Pizzacus** [comment]
I don't think it should be up to Tusky to block such instances, here is why:

1. It won't prevent such instances from existing and the content on it from being posted

2. Since the subject is super controversial, Tusky would lose a lot of users, not just people who post these kinds of stuff but also people who support being neutral towards them

3. There would likely be a fork removing the block anyway

4. Maintaining a list of blocked instances is a BIG responsibility, since we're talking about blocking them from an entire app, the potantial harm done by an unjustified block would be enormous

5. Because of that, a list of guidelines would need to be made and community consensus would be required which would be a HUGE effort for something that isn't very necessary in the end.

Tusky, as a Mastodon app, shouldn't try to influence the community. We use Mastodon because of its decentralised nature, so if a big app uses its influence to affect the community as a whole, don't we harm the very nature that makes the Fediverse so special? 

I am sorry for replying while you requested a Dev to do so, but I tried to keep this answer as neutral on the content itself as possible. This isn't about whether they're bad or not and I won't voice my opinion about that, but it's about the potential consequences of adding a new layer of moderation to the fediverse.

**Comment by matrix07012** [comment]
Why shouldn't Tusky block more instances if it already blocks one? There isn't a argument why it shouldn't.

**Comment by connyduck** [comment]
We will not block any existing Mastodon instance.

**Comment by Pizzacus** [comment]
@matrix07012 gab.com is not running on mastodon, they have their own software. As such, Tusky is probably not even compatible with it (at least that's the way I understood the situation), the rickroll is an easter egg in case anyone tried anyway

**Comment by RockyTV** [comment]
> We will not block any existing Mastodon instance.

> rainbowdash.net 	silenced 	Advice of toot.cat/cybre.space admins, GNUSocial apparent free speech zone**
>shitposter.club 	suspended 	Advice of toot.cat/cybre.space admins, GNUSocial apparent free speech zone**, hosts fake Gargron account
>freezepeach.xyz 	silenced 	Advice of toot.cat/cybre.space admins, GNUSocial apparent free speech zone**
>social.heldscal.la 	silenced 	Advice of toot.cat/cybre.space admins, GNUSocial apparent free speech zone**
>woofer.alfter.us 	silenced 	Advice of toot.cat admin, GNUSocial apparent free speech zone**
>social.au2pb.net 	silenced 	Advice of toot.cat admin, GNUSocial apparent free speech zone**
>gorf.club 	silenced 	Advice of toot.cat admin, GNUSocial apparent free speech zone**
>sealion.club 	silenced 	Advice of toot.cat/cybre.space admins, GNUSocial apparent free speech zone**
>gs.smu***.li 	suspended 	Advice of toot.cat admin, GNUSocial apparent free speech zone**, lolicon***
>unsafe.space 	silenced 	Advice of toot.cat admin, GNUSocial apparent free speech zone**
pa***.net 	suspended 	lolicon***
>wrongthink.net 	silenced 	GNUSocial apparent free speech zone**
>porntoot.com 	suspended 	Unflagged porn
>ediot.social 	silenced 	Apparent free speech zone**
>admins.town 	silenced 	Inter-admin politics that doesn't need to pollute the public timeline
>social.targaryen.house 	silenced 	Apparent free speech zone**
>noagendasocial.com 	silenced 	Apparent free speech zone**

I think this is enough. I'd just like to know why you're not going to do anything about existing fascist and pedophilia instances. As I've said before, it seems like you have some sort of personal problem with Gab, because you want to block it, but won't block other fediverse instances that are as offensive or worse.

**Comment by Yowlen** [comment]
I'd also be interested in knowing why blocking dangerous instances would fall outside the purview. Web browsers have built-in phishing protection, which basically blocks known harmful content, so why would such a thing not apply here too?

**Comment by ealgase** [comment]
> I'd also be interested in knowing why blocking dangerous instances would fall outside the purview. Web browsers have built-in phishing protection, which basically blocks known harmful content, so why would such a thing not apply here too?

Agreed, if Tusky is going to be blocking harmful instances, just blocking Gab isn't enough.

**Comment by Laurelai** [comment]
Hey @connyduck if you block these people from the repo they wont be able to comment or make spam issues. Just FYI.
