### ISSUE TITLE
[Feature Request] language filter

### ISSUE THREAD

**Issue by ebrulato** [tuskyapp/Tusky#135]
<< A panel may allow to select the language(s) that the user understand (eg. english, french, german, ...). The TL(s) will ignore the toots in other languages. >>

The objective is to provide a better (?) way to explore the Fediverse TL.

May be other people think this is a bad option, and may be this should be discussed with other users. I have sent an other feature request to add a "translate" button :)

It could be implemented with the language of the users (if it is available in the toots). But this could be awful if a user uses more than one language :(

**Comment by raphaelm** [comment]
I don't think there is a reliable way to detect the language of a toot

**Comment by alerque** [comment]
It would be relatively easy to get 85-90% accuracy for most languages, and with some extra monkey business you can get to about 95%. Mixed-language or very short ambiguous content tends to throw off at least some percentage using most detection methods.

That being said "easy" isn't "cheap" as far as code weight and would require running character and word set analysis on every string. At the very least this would need to be a optional routine.

Ideally the server itself would implement this so that it could be run once on each toot and the API would provide a field with the guessed language(s). This would save the clients having to do this work over and over again. Perhaps this should be opened as an issue on Mastodon itself.

**Comment by jemus42** [comment]
There might be a way do detect / filter languages now:

https://github.com/tootsuite/mastodon/commit/e4af4898de8ab962bf39ced5d31d88e3fd510538

**Comment by novoid** [comment]
The mentioned library from the tootsuite commit ist probably the best approach. It works very good for mastodon.social.

However, even [this ultra-simple approach using comparison of stopwords](https://github.com/novoid/lazyblorg/blob/master/lib/utils.py#L618) has a 99%+ chance of doing a correct classification for two languages like German and English with my blog software.

And even when there are occasionally false positives: when they are below a certain level, no-one will complain I guess. And when I want to avoid false positives for sure, I simply "subscribe" to all languages there are and therefore do not get a filtered view.

**Comment by charlag** [comment]
It seems like Mastodon language filters are applied server-side and we cannot even access them. I don't think it's feasible for us to implement it ourselves for other servers.

**Comment by novoid** [comment]
Implemented and executed on server-side does seem to be the best solution for this requirement anyway. Thanks for clarifying!
