### ISSUE TITLE
[Feature Request] Hashtag button to add symbol to selected text, not replace it

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1417]
Currently when selecting text and pressing hashtag button in Compose Toot screen, selected text is simply replaced with # symbol.

In my opinion, it's better to keep the text and just put symbol before it, effectively making a hashtag.

There are some problems though: what if several words are selected? Put symbol before the first one or make every selected word a hashtag? 

* * * *
- Tusky Version: 8.1-ce84233
- Android Version: 9.x Pie
- Android Device: Oneplus 5

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tak** [comment]
See https://github.com/tuskyapp/Tusky/pull/1277#pullrequestreview-241849747

**Comment by connyduck** [comment]
Yeah I guess everybody has a different opinion about this.
Please vote 👍 👎 on the issue so we see what is preferred

**Comment by monkeyless** [comment]
sounds like a good idea and same with "@" symbol

**Comment by guntbert** [comment]
This would break a general UI assumption: selected text is **replaced** by subsequent input.

**Comment by enbea** [comment]
> This would break a general UI assumption: selected text is **replaced** by subsequent input.

Well that is true but extra buttons aren't necessarily an input method. You can think of it like modifier buttons in a WYSIWYG editor that, instead of setting boldness or color, make the selected text into hashtags or mentions.

I'd also like to point out that this is not unprecedented with the closest example here being GitHub's comment editor which prepends "@" or "#" to the selected text when you click the mention or issue buttons.

Though personally I am in favor of prepending the character to each word ( or more specifically to any one or more characters in the selection that are not whitespace ).
