### ISSUE TITLE
Character limit not being detected correctly

### ISSUE THREAD

**Issue by measlytwerp** [tuskyapp/Tusky#1423]
The character limit for my instance isn't being detected correctly, it should allow me to post up to 1500 characters, but Tusky always shows 500.

* * * *
- Tusky Version: 8.1
- Android Version: 6.0.1
- Android Device: Lenovo YT3-X50F
- Mastodon instance (if applicable): auspol.cafe

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Your instance needs to have a parameter `max_toot_chars` in their instanceinfo https://auspol.cafe/api/v1/instance, otherwise Tusky can't pick it up. Contact your admin to change that.

**Comment by MasterGroosha** [comment]
@connyduck Unfortunately, "vanilla" Mastodon doesn't have such property. It would be nice to have an option like "ignore chars limit"

**Comment by charlag** [comment]
@MasterGroosha on "vanilla" mastodon you cannot change character limit either

**Comment by MasterGroosha** [comment]
@charlag That's why I'm talking about an option in Tusky. Some apps like Toot!, as far as I remember, show `-x/500` text but still try to send toot instead of prohibiting it.
And since Eugen is so stubborn about configurable/discoverable chars limit, this issue can be "easily" (in terms of algorithm) solved client-side.

Show `-x/500` text when text is more than 500 chars, but display a warning above with message "You have exceeded default chars limit. Tusky cannot guarantee message delivery" and still try to send a toot.
If success -> okay.
If fail -> default error message "failed to send toot".

**Comment by charlag** [comment]
@MasterGroosha we considered it and decided against it because people may not understand it (idea with message is neat but UI-wise the screen is cramped already). We said that the instances which have different limit use software which returns `max_toot_chars`. Ideally *all* servers should do it and if you change the limit you should also modify this return value. I think we already do everything that a proper client should do. We shouldn't try to match any half-configured server (we already have so many workarounds).

**Comment by MasterGroosha** [comment]
@charlag I understand your concerns, however "vanilla" Mastodon, which is popular, because it is, well, the original Mastodon implementation, doesn't have such option, so lots of servers who simply run pure Mastodon code and sync with tootsuite/mastodon repo, don't have `max_toot_chars` config option as well. That's the problem. You cannot just use Mastodon repo and have `max_toot_chars`, you need to fork the repo, add some code and keep syncing it with mainline, bothering with merge issues.

Anyway, I understand your opinion against adding "ignore chars limit" option, thank you for taking time to explain.
