### ISSUE TITLE
Tusky doesn't keep media upload order

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#1577]
When uploading media files with Tusky, the app orders media files in order they finished uploading, not how they were selected by me.
This is how I uploaded images (the second image finished uploading before the first one):
![изображение](https://user-images.githubusercontent.com/2780044/70050851-fe358780-15e0-11ea-8982-8b0212c7abc8.png)

This is how they appeared in timeline:
![Безымянный](https://user-images.githubusercontent.com/2780044/70051354-ea3e5580-15e1-11ea-9dbc-8fffce234671.png)

* * * *
- Tusky Version: 9.1-3c75ee7
- Android Version: 9.x Pie
- Android Device: Oneplus 5
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
@MasterGroosha I believe this will go away with #1541

**Comment by charlag** [comment]
@MasterGroosha can you confirm that it's fixed on nightly now?

**Comment by MasterGroosha** [comment]
@charlag Unfortunately, the issue is still present with Tusky 9.1-21a7201
Here are screenshotf of the process, tested on forced 2G connection:

![изображение](https://user-images.githubusercontent.com/2780044/72405890-8031d800-376b-11ea-9451-a5fcc65dd18b.png)
![изображение](https://user-images.githubusercontent.com/2780044/72405895-83c55f00-376b-11ea-96d9-302ff16892d3.png)
![изображение](https://user-images.githubusercontent.com/2780044/72405899-8758e600-376b-11ea-83c7-17c5238f5ba6.png)

**Comment by charlag** [comment]
I tested it and it seems like we do everything right - e.g. we pick 2 photos. We give each a local id: `local1`, `local2`. When `local2` finishes it gets id from the server: `server1`. When `local1` finishes it gets id `server2`.
I debugged it and to the server we send `[server2, server1]` (which corresponds to `[local1, local2]`), so in order they've been picked. I think that  Mastodon may have something to do with it. Would be nice if you could test it with some other client.

For the record, to test it I put `sleep()` into `ProgressRequestBody` callback but only if it's the first photo so that the first photo always finishes the last.

**Comment by connyduck** [comment]
What server did you post this on? @MasterGroosha

**Comment by MasterGroosha** [comment]
@connyduck https://mastodon.ml (if you need to register on that instance, please let me know)

**Comment by charlag** [comment]
I believe this is fixed now
