### ISSUE TITLE
Network error message on profile doesn’t work well in landscape

### ISSUE THREAD

**Issue by ariasuni** [tuskyapp/Tusky#1618]
Because on the profile screen there is the tabs bar, in landscape the button is flattened and almost unreadable, at least with my screen size:

![Screenshot_20200102-182128_Tusky](https://user-images.githubusercontent.com/2446451/71767959-23842100-2f12-11ea-8ecb-c6ab64fff4bb.png)

To reproduce, just put your telephone in landscape, disable network/enable airplane mode, and try to open your profile or somebody else’s, and scroll to the bottom.

I think the error message should make a better use of the available horizontal space (mockup):

![Screenshot_20200102-182128_Tusky_mockup](https://user-images.githubusercontent.com/2446451/71767960-241cb780-2f12-11ea-8060-97bbe943a9e3.png)

* * * *
- Tusky Version: 9.1/9.1-352ff3a2
- Android Version: 9
- Android Device: One Plus 5

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I've tried to make a simple fix but turns out that the image is a part of the TextView.
So we have to either separate them into two different views.

I also tried to change orientation of the textView instead but it doesn't help much.

I tried to change orientation of both text view and the whole view but it didn't work either (the button was not sized properly).

So I think the best solution would be to split image into separate view.
@connyduck

**Comment by connyduck** [comment]
Have you tried detecting the orientation programmatically and then setting the image as `drawableStart` or `drawableTop` accordingly?

**Comment by charlag** [comment]
Yes, that's what I did. It's not enough because the image consumes the full high anyway and the button below would be smashes. It would be smashed on the right too but because of the text.

**Comment by connyduck** [comment]
Yes, then lets add an additional ImageView
