### ISSUE TITLE
The text is not shifted.

### ISSUE THREAD

**Issue by bezuhv** [tuskyapp/Tusky#1774]
The text is not shifted. Screencast: https://cloud.mail.ru/public/YSo7/SDpAryx1w

* * * *
- Tusky Version: 11.0
- Android Version: 7.1
- Android Device: Lenovo Tab3
- Mastodon instance (if applicable): any

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I'm pretty sure it's a bug in Android. I think there's a limit on text view height. You cannot scroll to your cursor manually either?

**Comment by bezuhv** [comment]
I can’t do it manually.  This is not an android to blame, since the same error occurs on the second device.19:23, 4 мая 2020 г., Ivan Kupalov <notifications@github.com>:
I'm pretty sure it's a bug in Android. I think there's a limit on text view height. You cannot scroll to your cursor manually either?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
_________________Виталий Безухhttp://mssg.me/bezuhv

**Comment by TheOtherDoctor** [comment]
Thanks for adding the illustrative screencast; Looks to me this is the problem I reported as #1765 -  @bezuhv, could you please have a look if the description there matches your observation?
It would also help to know if you are using a similar system/setup, such that we might identify some common aspects... to identify the circumstances under which this can be reproduced - and fixed. ;-)
Anyway, since it took me many trials to finally open the screencast, it might help to add a bit more verbal description of the observed problem here to make it easier to identify the context.

**Comment by bezuhv** [comment]
> Thanks for adding the illustrative screencast; Looks to me this is the problem I reported as #1765 - @bezuhv, could you please have a look if the description there matches your observation?
> 
> As far as I can see, both issues are filed for similar system (Lineage14.1 is equiv to Android 7.1), such that we might be on the way to identify some common aspects... ;-)
> Does screen orientation have an effect for you, or the choice of screen keyboard app?
> 
> Anyway, since it took me many trials to finally open the screencast, it might help to add a bit more verbal description of the observed problem here to make it easier to identify the context.

**Comment by bezuhv** [comment]
Screen orientation is not affected.
I don’t know what else to add.

**Comment by charlag** [comment]
I struggle to find the original issue but it's a bug in Android which doesn't support text fields which are too long.
Tusky is not designed to post 9k long posts and we also fixed it on our side as much as we could. I'm afraid it won't work on your Android version.
