### ISSUE TITLE
Cannot browse the entire history of a user's posts

### ISSUE THREAD

**Issue by dbogdanov** [tuskyapp/Tusky#1827]
Checking the posts of a particular user (the "POSTS" tab) it seems I cannot browse their entire history, only the latest posts. Opening the same user profile in the browser, I see all the posts. Is this intentional? 

* * * *
- Tusky Version: 11.0
- Android Version: 10
- Android Device: Pixel 3a

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
> in the browser

Does that mean the webapp or the public user page?

When the user is on another instance its is very likely that not all posts federated to your instance.  Of course you see them on the public profile page, because that one has all the data. Nothing we can do, that is expected behavior. If you see posts in the webapp or another mastodon client (being logged in with the same user) and not in Tusky, thats a bug on our side. Please provide details on the instances/users involved.
