### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by clarkenciel** [tuskyapp/Tusky#189]
I don't know how viable this is, but here goes: Many instances have started to use customized colorschemes, icon styles, and column names. Is it possible for tusky to preserve those styles when "logged in" to such instances?

**Comment by Vavassor** [comment]
It isn't possible to preserve the styles. Since I'm sure the existing ones are some combo of HTML & CSS, they work differently than android themes. They would also need to be in the Mastodon API or in some centrailised site to download from.

I've speculated about ways to implement custom themes for Tusky in general, but it's difficult given how android handles theming by design. The light/dark themes right now are basically baked in when the application is built, but when it's running there's no way to add new themes.

It could be done by making a **lot** of custom code that would exhaustively load values for every attribute in every view type used in the whole app. So, like, it _is_ possible but a lot of tedious work would have to get done to make it happen.

**Comment by clarkenciel** [comment]
I thought that would be case. It sounds like at the very least there would need to be a fair bit more research around the use case for this kind of thing and refinements in the main app (as you say). Thank you for taking the time to respond to this though! and if it seems untenable feel free to close.

**Comment by SkyzohKey** [comment]
Or we can make a PR on Mastodon admin interface that allow to publish custom colors on the api, then get those colors at runtime (cache them in preference) and restart the app taking in account the new colors. :)

**Comment by Tak** [comment]
At minimum, this would need server side support
