### ISSUE TITLE
accessibility option for sunlight readability / light theme contrast

### ISSUE THREAD

**Issue by sireebob** [tuskyapp/Tusky#1971]
related to #1687, the light theme causes more eye strain than necessary when trying to read the app in sunlight even briefly, compared to most apps with a light theme, and there appears to be no workaround. this is because tusky doesn't provide as much contrast between light background and dark text as other apps do.

i understand the bluish tint is intended, so that being the case, could we get an accessibility toggle that makes the background colors white when the light theme is in use? this would apply to the system design as well, when not in dark mode.

if you don't have time for this but might be willing to accept a PR, i can try submit one.

thanks!

- Tusky Version: 12.1
- Android Version: 10.0, LineageOS-based
- Android Device: OnePlus 5

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by bhtooefr** [comment]
I'm going to throw in a comment here - essentially, I don't think #2025 fully solves this issue, for another reason entirely.

I just put Tusky on an e-ink device, and what would be optimal is a White counterpart to the Black theme. (The device has a "whiten dark backgrounds" mode, but this does things like make the Android top bar unreadable due to Tusky keeping that dark even on light themes.)

This is slightly different from the original accessibility issue, but would more completely resolve this, as well as improve experience for users of e-ink devices.
