### ISSUE TITLE
Building Tusky from source

### ISSUE THREAD

**Issue by am2222** [tuskyapp/Tusky#2042]
Hi,
This not actually an issue, so I hope I am not breaking any rules. I wanted to build the app from scratch and I am using this command
```
./gradlew bundleGreenRelease
```
Which seems it is supposed to build an unsigned version of the app. it makes it with no issues but it is not installable. (I have removed the original version from my phone)
I also looked at bitrise configurations and this line caught my eyes ```- apk_file_include_filter: "*.aab"```, am I doing anything wrong?
This is my github action
https://github.com/am2222/Tusky/blob/develop/.github/workflows/blank.yml

* * * *
- Tusky Version: latest version
- Android Version: 9
- Android Device: Samsung S8+
- Mastodon instance (if applicable): 

- [-] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
-

**Comment by connyduck** [comment]
`bundle` builds an AppBundle (*.aab file), which is not for installing on a device, but for upload to Google Play. I think you want an *.apk file. Try `./gradlew assembleGreenRelease`

**Comment by am2222** [comment]
@connyduck Thanks, I am running it now

**Comment by am2222** [comment]
@connyduck It just finished the build but I still have the same issue. 
I am using this apk `app/build/outputs/apk/green/release/app-green-release-unsigned.apk`, Am I using the correct apk file?

**Comment by connyduck** [comment]
Yes file looks correct. Why is it not installable? Maybe Google Play protect is blocking it?

**Comment by a1batross** [comment]
Because it's unsigned, it said in it's name. And you can't install unsigned APKs on Android.

To sign APK, generate a keystore first:
`keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000`

Then sign it:
`apksigner sign --ks my-release-key.keystore --ks-key-alias alias_name --ks-pass PASSWORD --key-pass PASSWORD --in unsigned.apk --out signed.apk`
