### ISSUE TITLE
uploading images over slow connection fails after a certain time, although the upload is making slow progress all the time

### ISSUE THREAD

**Issue by rohieb** [tuskyapp/Tusky#2226]
Sometimes I'm in areas with slow internet (say, in a random village somewhere in rural Germany, but this can probably be reproduced with a WiFi AP throttling the upload to ~28 kbps). When adding images to a post, the circle that shows the upload progress is making slow progress all the time, but the upload fails nevertheless after a certain time (could be around 1 minute). It seems to me that there is a hard timeout in Tusky until which the upload must be finished, which has the effect that I cannot upload any images (in full size) because the files are too big to fit over the small connection in the required time. 

Could the situation could be improved by applying the timeout only when no more data is received from the server? I.e. only start the timeout if the upload progress bar is stuck and no longer moving.

* * * *
- Tusky Version: 15.1
- Android Version: 10
- Android Device: Nokia 3.1
- Mastodon instance (if applicable): chaos.social

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment]
I checked how our timeouts are configured.
We define read and write timeouts as 30s. There's also call timeout (the whole request) and connect timeout (time until connection is established). Call timeout is not enabled by default and connect timeout is 10 seconds.
Hard to say without some logs but I think that the other side might be closing the connection earlier than we realize that, don't know why it would be otherwise.
