### ISSUE TITLE
Disappearing downloaded media

### ISSUE THREAD

**Issue by anedroid** [tuskyapp/Tusky#2262]
I noticed that downloaded images and videos are deleted automatically after some period of time. If this app's behavior is intentional (eg. for save device storage), please add option to control it and turn it off by default.

* * * *
- Tusky Version: 15.1
- Android Version: 11
- Android Device: ocean

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (I found one similar issue, but I suppose that's not a duplicate: [#2230](https://github.com/tuskyapp/Tusky/issues/2230))

**Comment by TheSandBoxMKG** [comment]
I've had this issue since I got my Android 10 Motorola One Fusion non-plus and upgrading to Android 11 doesn't help.

**Comment by connyduck** [comment]
By downloaded media, you mean media downloaded with this button?

![Screenshot_20220301_195343](https://user-images.githubusercontent.com/10157047/156231229-b57aa37f-005e-4550-a7cd-19e0265973ca.png)

**Comment by connyduck** [comment]
Ok, looks like we are running into this issue https://stackoverflow.com/questions/46501822/downloaded-files-get-deleted-automatically
I'll try to fix it.

**Comment by connyduck** [comment]
According to documentation, saving downloads in the 'Downloads' folder will have them stay forever, while downloads in custom directories will be deleted after 7 days on Android 10+.
Tusky, weirdly enough, saves downloads in a custom folder when you download media from the media viewer, but when you use "download all media" on a status, it saves them in the 'Downloads' folder.

1) Both these download methods should save to the same location
2) Easy fix is always using the Downloads folder everywhere, I think I will go with this
3) If we want a custom folder & have the downloads stay forever, we need to use a different Api, because there seems to be no way to tell `DownloadManager` to leave the downloads alone.

**Comment by TheSandBoxMKG** [comment]
@connyduck Huh, "Download all media" do you say? Where is that option located? Because I cannot seem to find it. I'm in Tusky 16.0 from F-Droid.
