### ISSUE TITLE
Allow activities to be synced

### ISSUE THREAD

**Issue by Pangoraw** [tuskyapp/Tusky#280]
Right now when an action is taken on a user profile for example, the action is not synced with the main timelines.

Here are the actions that should be synced :

- When following a user, add his statuses to the home timeline
- When unfollowing/muting/blocking a user, remove his statuses from the home timeline
- When fav or boosting, show the status as fav/boosted in the home timeline

I don't know how such thing can be done. Do you have any clue ?

**Comment by Vavassor** [comment]
The second bullet point is something I've already done for blocking and muting across fragments in 5179d7e9b32ec191268147df3c66ee02b814457b with a listener system. I think to work across activities and fragments it would be better to switch to [Broadcasts](https://developer.android.com/guide/components/broadcasts.html).

The second and third bullet points are easier, because removing posts and switching a post's state isn't too hard. For a given timeline, you basically just get the adapter on the ```RecyclerView``` and search its posts for a given status ID or account ID. Then make whatever change to the post and call ```notifyItemChanged``` or ```notifyItemRemoved``` for each of those post positions to update the view with the current values in that ```Status```.

Adding statuses is harder because you have to fetch bunches of statuses and patch them in with the ones already loaded in some way. Forcing a full refresh would be easier but also would make you lose your position in every timeline. Which would be probably more annoying than not having the new statuses at all.

**Comment by Pangoraw** [comment]
I have a first version working for unfollow/mute/block. Unfollowing only remove statuses from the home timeline. 

Muting and blocking should remove the statuses from the three main timelines, right ? I don't really get the difference between muting and blocking.

I will prepare a pull request so we can discuss about it.

**Comment by charlag** [comment]
It should be done now I guess, feel free to reopen if something is not implemented. Not sure we refresh timeline on follow (wouldn't work anyway) but we surely remove things on block, refresh when toot is posted and sync favs/boosts.
