### ISSUE TITLE
local and federated tabs are empty

### ISSUE THREAD

**Issue by ColonelSanderson** [tuskyapp/Tusky#2805]
When I open the local or federated tabs, I see the "Nothing is here" placeholder. I'm unable to see any toots in the app but they display fine in the browser. I've reinstalled with no change.

* * * *
- Tusky Version: 19.0
- Android Version: 13
- Android Device: Pixel 6
- Mastodon instance (if applicable): mastodon.social

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Mastodon.social has disabled the local and federated timelines in order to lessen the server load.

**Comment by vwbusguy** [comment]
Kind of.  I'm on mastodon.online and I do see federated and local timelines from the web view and PWA, but it's more like a stream of incoming posts.  I'm not sure if how these work changed with v4rc2 but it looks like, at least on the main sites, these timelines are streamed as messages come in rather than cached and delivered in bulk.

**Comment by connyduck** [comment]
Ok then the Rest API has been disabled and the streaming one still works, but Tusky uses only the Rest API.
