### ISSUE TITLE
Allow one to display alt text / image descriptions without centered aligment

### ISSUE THREAD

**Issue by villares** [tuskyapp/Tusky#2819]
I sometimes post images that contain Python code, so I noticed that when adding Python code to the alt/descriptions it can become unreadable because the centered alignment spoils the indentation.

* * * *
- Tusky Version: 19.0
- Android Version: 11
- Android Device: moto G8

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Is there a reason we show descriptions centered @charlag? We could just start-align them all.

**Comment by charlag** [comment]
@connyduck I don't think there's any reason besides aesthetics but it would also not change how the screen reader narrates the code

**Comment by moeffju** [comment]
Start-aligned ragged text is also consistently easier to read, so I would second this request purely for aesthetic reasons as well. At the same time I would ask that some more padding be added (due to screen borders, especially rounded corners) and/or the width of the alt text be limited, also for easier reading.
