### ISSUE TITLE
Timeline background sync

### ISSUE THREAD

**Issue by intrnl** [tuskyapp/Tusky#2898]
It would be cool if Tusky can do a background sync of my timeline, the current experience is sort of lacking as you'd have to pull to refresh, and keep tapping on the load more button to catch up with the posts that are between where you are now and the very latest posts.

(Additionally, with the current solution, you might not catch up with all the posts as there's a limit as to how far you can go down in the timeline if you had started from the top, something you'll definitely encounter if you've gone for a day or two)

* * * *
- Tusky Version: 19.0
- Android Version: Android 12
- Android Device: realme 9 4G
- Mastodon instance (if applicable): fosstodon.org, applicable to all however

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ScottESanDiego** [comment]
Yes!  I was just about to make a Feature Request for this, so thanks for beating me to it!

The ideal experience would be something like Talon (for birdside), where it periodically refreshes the timeline so that when you open the application next you're at the last-viewed post, and all the posts since then are already loaded "above" where you are.  No more "Load more" to fill things in, as it would have happened every x-minutes in the background already.

**Comment by Tak** [comment]
Requested timeline behavior changes are being gathered in #2788
