### ISSUE TITLE
Display @ mentions outside the content warning

### ISSUE THREAD

**Issue by Vavassor** [tuskyapp/Tusky#292]
This is how the website displays them. Also, it makes it clear that the post is a reply and who it's replying to without having to "show more".

**Comment by charlag** [comment]
@connyduck still relevant? Did you decide against it?

**Comment by connyduck** [comment]
Well I would like Tusky to be quite similar to the web, and this is definitely something we should do, but it doesn't have any priority.

**Comment by ariasuni** [comment]
I thought this might not be too complicated to do so I checked the code a bit but I couldn’t find where toot displaying is done. Do you think it would be easy to do for someone not familiar with the code base? I’d like to have some pointers, and try to do that if I find the time.

**Comment by charlag** [comment]
@ariasuni I think it's totally doable and I would like to help!
I think you need to look into [StatusViewHolder](https://github.com/tuskyapp/Tusky/blob/89f93eab853d99a92340dc2d5240192f098d4a7a/app/src/main/java/com/keylesspalace/tusky/adapter/StatusViewHolder.java)
If you need any additional help feel free to ping me here, on Masto or in our Riot room!

**Comment by charlag** [comment]
(or base view holder)

**Comment by ariasuni** [comment]
So I looked a bit at the code and managed to do something really buggy. I’m not sure how I can do that properly.

Here’s what I found:

- Content visibility is changed [here](https://github.com/tuskyapp/Tusky/blob/59257c7af4bbca6e068d4868126669df20294308/app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java#L402), [here](https://github.com/tuskyapp/Tusky/blob/59257c7af4bbca6e068d4868126669df20294308/app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java#L405) and [here](https://github.com/tuskyapp/Tusky/blob/59257c7af4bbca6e068d4868126669df20294308/app/src/main/java/com/keylesspalace/tusky/adapter/StatusBaseViewHolder.java#L412).
- Toot text is modified to make links/hashtags/mentions clickable [here](https://github.com/tuskyapp/Tusky/blob/59257c7af4bbca6e068d4868126669df20294308/app/src/main/java/com/keylesspalace/tusky/util/LinkHelper.java#L65).

I tried to change the text of the view instead of changing the visibility of the text. So here’s what I did:

- filter the toot text to only have mentions (it may it easiest to use the mentions array directly)
- fill it into the view with `LinkHelper.setClickableText()` and retrieve it with `.getText()`
- fill the normal text into the view and retrieve it too
- then, use `setText()` with one or the other text I retrieved when clicking on the button

But it needed some type casting (to store both texts as members of `StatusBaseViewHolder`). And the different string types used in Android aren’t always clear.

Also, it only worked in threaded view and not right away, only after having clicked on the spoiler button so I guess there are other places to look at.

**Comment by charlag** [comment]
Hey, thanks for the changes!
From your code I see that you use mentions array directly which is probably the easiest and the most sane option. I'm not sure which type casting you're referring to, tbh. I looked only briefly but it looks fine and should work fine too.
For the future I would recommend opening a pull request. Even if it's WIP just make it clear. It's easier to review changes and keep track of all requests there (I stumbled upon this comment by accident now).

**Comment by connyduck** [comment]
I think you are on the right track, but this should be even simpler.
- definitely use the mentions array and don't parse anything
- leave the `setClickableText` method alone, create a new one that takes a `TextView`, the mentions array and a `LinkListener` and build the needed Spannable in there.
