### ISSUE TITLE
Media upload fails for m4a audio file

### ISSUE THREAD

**Issue by connyduck** [tuskyapp/Tusky#3189]
Original report: https://mastodon.social/@Teratogenese@mamot.fr/109695671921182591
Steps to reproduce: Try to upload [this file](https://connyduck.at/Ring.m4a). Upload fails with "Video has no video stream".

This happens due to `ContentResolver.getType` returning the wrong mime type after the file was copied.
In [`MediaUploader.prepareMedia`](https://github.com/tuskyapp/Tusky/blob/abca91a420939b058d59b8ccb6bb3ca9fdc96fab/app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt#L161) the extension is correctly detected as .m4a and the type as `audio/mp4`. Then the file is copied to the cache dir. And later, in [`MediaUploader.upload`](https://github.com/tuskyapp/Tusky/blob/abca91a420939b058d59b8ccb6bb3ca9fdc96fab/app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt#L250), the extension is detected as .mp3 and the mime type as `audio/mpeg`. This makes the file upload with the wrong type and the server can't process it. With the right extension and type upload succeeds.

Not sure why this happens and how to properly fix this. One way would be to forward the initially detected type to the upload, but that is quite a big change as it would propagate all the way to drafts.
Ideas and help very much welcome..

* * * *
- Tusky Version: 20.0
- Android Version: Android 11
- Android Device: Fairphone 4
- Mastodon instance (if applicable): mastodon.social

**Comment by nikclayton** [comment]
Hmm. When I right click on https://connyduck.at/Ring.m4a and do "Save link as..." it prompts me to save it as "Ring.mp3", not "Ring.mp4".

That doesn't change anything about the content of the file (verified by fetching it with `curl`, file sizes are the same and `cmp(1)` reports no differences).

`file(1)` reports `ISO Media, MP4 v2 [ISO 14496-14]` in both cases.

**Comment by nikclayton** [comment]
By the time the file is copied to the cache dir it has the .mp3 extension.

I put a breakpoint on `ComposeViewModel.addMediaToQueue`, and after this line:

```
stashMediaItem = mediaItem`
```

the value of `stashMediaItem.uri` is `content://com...../fileprovider/*/randomTemp<digits>.mp3`

**Comment by nikclayton** [comment]
The conversion to `.mp3` extension is happening in `prepareMedia`.

I copied the .m4a file to the emulator, and verified it's still got the `.m4a` extension.

In `prepareMedia` this code:

```
             mimeType = contentResolver.getType(uri)

             val suffix = "." + MimeTypeMap.getSingleton().getExtensionFromMimeType(mimeType ?: "tmp")
```

Sets `mimeType` to `audio/mpeg`, and the suffix to `.mp3`.

At this point, `uri` is `content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FRing.m4a` (i.e., `uri` definitely has the `.m4a` extension).

**Comment by connyduck** [comment]
Yes. But why is it like that and how do we work around it?

**Comment by nikclayton** [comment]
`getType()` calls through to `MimeTypeMap()` to get a type mapping.

Some hacky code to dump what it thinks a `.m4a` is:

```
val map = MimeTypeMap.getSingleton()
val ty = map.getMimeTypeFromExtension("m4a")
Log.d(TAG, "m4a has mimetype $ty")
val ext = map.getExtensionFromMimeType(ty)
Log.d(TAG, "ty $ty maps back to ext $ext")
```

and it logs:

```
m4a has mimetype audio/mpeg
audio/mpeg maps back to ext mp3
```

So it's determined the wrong mime type (according to https://en.wikipedia.org/wiki/MP4_file_format `.m4a` is a non standard but common extension, and the mime type should be `audio/mp4`.

I'm confused about the first comment, which says

> In [MediaUploader.prepareMedia](https://github.com/tuskyapp/Tusky/blob/abca91a420939b058d59b8ccb6bb3ca9fdc96fab/app/src/main/java/com/keylesspalace/tusky/components/compose/MediaUploader.kt#L161) the extension is correctly detected as .m4a and the type as audio/mp4

That's not what I'm seeing, the information is already wrong in `prepareMedia`.

**Comment by nikclayton** [comment]
Ah, `MimeTypeMap` is internally inconsistent:

This code:

```
Log.d(TAG, "audio/mp4 is ${map.getExtensionFromMimeType("audio/mp4")}")
```

Shows `audio/mp4 is m4a`.

So `MimeTypeMap` can go `audio/mp4` -> `m4a`, but it doesn't go `m4a` -> `audio/mp4`.

**Comment by nikclayton** [comment]
Nothing relevant in the Android issue tracker (https://issuetracker.google.com/issues?q=componentid:(192786%20%7C%20192805%20%7C%20192705%20%7C%20192792%20%7C%20192644%20%7C%20192694%20%7C%20192710%20%7C%20192810%20%7C%20192634%20%7C%20192698%20%7C%20192706%20%7C%20470386%20%7C%20192815%20%7C%20192715%20%7C%20192720%20%7C%20192711%20%7C%20192629%20%7C%20192643%20%7C%20192693%20%7C%20192639)%20mimetypemap).

**Comment by nikclayton** [comment]
Quick summary:

In the current code, for a file ending `m4a`, this:

```
mimeType = contentResolver.getType(uri)
val suffix = "." + MimeTypeMap.getSingleton().getExtensionFromMimeType(mimeType ?: "tmp")
```

sets `mimeType` to `audio/mpeg` (incorrectly), and `MimeTypeMap` converts that to `mp3`.

`contentResolver.getType(uri)` defers to the `getType()` implementation in each `ContentProvider`.

In the case of files being loaded from the the `Downloads` directory, that's `DownloadProvider` (because the URI starts `content://com.android.providers.downloads.documents`).

`DownloadProvider.java` is https://android.googlesource.com/platform/packages/providers/DownloadProvider/+/refs/heads/master/src/com/android/providers/downloads/DownloadProvider.java,

So I think that's where the wrong mime type is coming from.

**Comment by nikclayton** [comment]
It's not coming from the download provider database.

I pulled it locally (it's in `/data/data/com.android.providers.downloads/databases/downloads.db`) from the emulator, and inspected it using local sqlite3 tools.

The `Ring.mp4` file was not in the database, because I copied it to the filesystem directly, instead of downloading it to the device. So the mime type must be coming from somewhere else.

**Comment by nikclayton** [comment]
If I'm reading the code properly, if it's not in the database then `DownloadProvider` throws an exception. This is caught in `ContentResult.getType()`, and it falls back to calling `getProviderMimeTypeAsync()`, with this code:

```
            ActivityManager.getService().getProviderMimeTypeAsync(
                    ContentProvider.getUriWithoutUserId(url),
                    resolveUserId(url),
                    new RemoteCallback(resultListener));
```

That eventually calls through to `ContentProviderHelper.getProviderMimeTypeAsync()`

**Comment by nikclayton** [comment]
However, that probably doesn't matter. Because the current code makes a temporary copy of the file. So even if it's a file that was downloaded, or a file that was put on the device in some other way (e.g., by copying to the emulator filesystem, or an on sdcard on physical hardware), the code is eventually going to hit this code in `upload()`:

```
            var mimeType = contentResolver.getType(media.uri)
            val map = MimeTypeMap.getSingleton()
            val fileExtension = map.getExtensionFromMimeType(mimeType)
            val filename = "%s_%s_%s.%s".format(
                context.getString(R.string.app_name),
                Date().time.toString(),
                randomAlphanumericString(10),
                fileExtension
            )
```

I tried that with a file that I copied to the device. Debugging shows on entry to the function, `media.uri` was `content://com.keylesspalace.tusky.fileprovider/*/randomTemp19122282289595499927.m4a`.

I.e., the temporary file **had the correct extension**, because it's just been copied over raw (because it wasn't in the downloads database).

Because the `content://` URI is `fileprovider`, the line `var mimeType = contentResolver.getType(media.uri)` calls through to `androidx.core.content.FileProvider.getType()`.

That code is https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/core/core/src/main/java/androidx/core/content/FileProvider.java#556.

And if you look at that, you'll see that it does:

```
    public String getType(@NonNull Uri uri) {
        // ContentProvider has already checked granted permissions
        final File file = mStrategy.getFileForUri(uri);

        final int lastDot = file.getName().lastIndexOf('.');
        if (lastDot >= 0) {
            final String extension = file.getName().substring(lastDot + 1);
            final String mime = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
            if (mime != null) {
                return mime;
            }
        }

        return "application/octet-stream";
    }
```

And as https://github.com/tuskyapp/Tusky/issues/3189#issuecomment-1396188791 shows, if you call `getMimeTypeFromExtension("m4a")` you get back `audio/mpeg`, **not** `audio/mp4`.

**Comment by nikclayton** [comment]
This matches what happens if you do "Get info" on the file in "Files" app on the emulator.

Note the mimetype shown on this screenshot.

<img src="https://user-images.githubusercontent.com/773100/213436519-01690d93-b18b-4630-94e8-a72b3bb3b02c.png" width="60%">

**Comment by nikclayton** [comment]
Of course, it's been nagging at me as to why, when asked to save https://connyduck.at/Ring.m4a, Chrome on both desktop and Android prompt to save the file as `Ring.mp3`.

@connyduck your server is returning an `audio/mpeg` mime type;

```
% curl -v https://connyduck.at/Ring.m4a -o Ring.m4a
[...]
< HTTP/1.1 200 OK
< Date: Thu, 19 Jan 2023 11:58:01 GMT
< Server: Apache
< Strict-Transport-Security: max-age=133333337; includeSubDomains; preload
< Upgrade: h2
< Connection: Upgrade
< Last-Modified: Tue, 17 Jan 2023 18:41:44 GMT
< ETag: "21415e-5f27a0d287a41"
< Accept-Ranges: bytes
< Content-Length: 2179422
< Content-Type: audio/mpeg
```

That's probably not helping -- it explains why the DownloadProvider has the wrong mimetype.

**Comment by nikclayton** [comment]
That notwithstanding, given `MimeTypeMap` returns the wrong values, this will have to be fixed with content sniffing.
