### ISSUE TITLE
Boosting a post that's just an image shows an empty dialog

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3308]
Boost a post like https://mstdn.social/@Dark_phoenix/109831170941464918 which is an image only, no text.

If you have confirmations turned on you are shown an empty confirmation dialog.

![Screenshot_20230211-204503](https://user-images.githubusercontent.com/773100/218278194-f3e78572-30f9-423b-8189-e0b5f7c53ba4.png)

* * * *
- Tusky Version: 21

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
The actual fix would maybe be rather simple (in StatusBaseViewHolder#showConfirmReblogDialog).

However there are a number of questions that popped up for me when working there (sorted from big to small):

* Do we need these confirmation dialogs for boost and favorite at all? I guess it's yes because otherwise you wouldn't necessarily know what that button does? However this solves a help question with an "Are you sure" dialog. And "Are sou sure" is not necessary here as it can be easily undone (just tap button again).
* This dialog shows _only_ the text. For example a poll is also missing. Also if there is (a bit of) text and image it is odd that the dialog only shows the text. I guess if it shows any content it should show all of it (which would make much more complicate).
* If images are not shown in the dialog, what should be shown instead as text? "an attachment"? The alt text?
* If this is an "Are you sure" dialog, does it need a title? But I'm pretty sure it also needs a cancel / No button.
* The dialog shows _all_ text. This might be too much to show on a screen.

So, actually, I have no real solution here.
I would remove the dialog/option but I guess we can't do that as it is already present and might be used by some?

Maybe a compromise would be:
* Only show a real "Are you sure" dialog (without content but with title).
* This dialog could then also have a checkbox for deactivating it/the option.

**Comment by nikclayton** [comment]
> Do we need these confirmation dialogs for boost and favorite at all?

Yes, but for (I think) a more important reason than the ones you've listed. These buttons cause a change to the user's data that is visible by other users.

Bookmarking doesn't, so that doesn't need a confirmation. And replying requires the user to complete multiple steps to confirm they want to reply.

But these two, by default, should require the confirmation.

But this doesn't necessarily have to be a dialog. What if it popped up a menu where the option was "Boost as [account]" (https://developer.android.com/reference/android/widget/PopupMenu) ?

1. That would require the same number of taps as exist right now to boost with confirmation
2. The menu would be clearly attached to the button, so it's clear which status is involved -- no need to duplicate the status.
3. If the user has multiple accounts this could show multiple options, allowing them to boost a status from one of their other accounts, without needing to switch (this would also solve https://github.com/tuskyapp/Tusky/issues/2793)

Interaction rules would be:

- If the user has "confirm boost" enabled and one account, show the menu on click
- If the user has "confirm boost" disabled and one account, boost immediately on click
- If the user has "confirm boost" disabled, and multiple accounts, boost immediately on click, show the menu on long-click only

And do the same thing for favourites.
