### ISSUE TITLE
Show help text on empty home timeline

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#3408]
When starting Tusky for the first time for a new account everything will be empty.

It would be helpful to show a help message for this case on what to do next.

Here is my first draft for this:

![Screenshot_20230302_104323](https://user-images.githubusercontent.com/1618905/222393427-d76a5414-1bda-4af9-9334-6e76194a33e8.jpg)

You could think of similar help messages on other screens (e. g. an empty notfications timeline).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
Created from https://github.com/tuskyapp/Tusky/discussions/3144 and loosely related to https://github.com/tuskyapp/Tusky/issues/3213

**Comment by Lakoja** [comment]
Loosely related: https://github.com/tuskyapp/Tusky/issues/111 (general introduction screen)

**Comment by nikclayton** [comment]
Couple of thoughts.

1. Yes to the general idea, as it improves the onboarding flow.

2. What if instead of showing this like, this showed as a status, that appeared to be from the Tusky account?

There's an obvious downside to this -- it might confuse users ("Why am I seeing a post from @Tusky when I don't follow that account?").

I think it's possible that the text in the status could answer that question, and the clicking the buttons on the fake status (boost, favourite, etc) could pop up a dialog that explains what they do.

Honestly, I'm not convinced I like this idea, as I can see assorted failure modes. For example, how do we teach the user what the UI does if they do have a full timeline and they never see this fake status? But then, if they have a full timeline they're probably familiar with Mastodon general features already, and the UI tour may not be relevant for them.

3. Separate to that though, what should the intro flow look like?

There's at least two different users;

1. New (probably determined by the count of everything they can follow (people, hashtags, ...) being 0, or maybe it's just a question that's asked during onboarding, "Do you want the "New user" experience?")
2. Everyone else

For new people can we give them a guided experience? For example:

- Hide the home timeline (there's nothing for them to see if they're not following anything)
- Keep notifications (maybe they're not following, but they're posting, and they get notifications about that)
- Open the search first, with a guided path to finding people or hashtags to follow?
- Check their account info, and prompt them to complete some of it?

I absolutely **am not** suggesting that Tusky should do some sort of "Hey, your profile is only 80% complete, why don't you fill in your profile description?" or "You're not following any hashtags, do you want to try?" type of nagging on regular use. Definitely not.

But for new users maybe we can give them an (optional) checklist of things to try out?

**Comment by Tusky** [comment]
You tagging me just now did confuse me, and I'm not even a user! :P

**Comment by Lakoja** [comment]
If this is liked (merged) the next step could be the private message view. Especially as that could do with some explanation on "What is private message and how to create one?".
