### ISSUE TITLE
When logging out: all user data is erased

### ISSUE THREAD

**Issue by Lakoja** [tuskyapp/Tusky#3417]
When logging out from an account Tusky deletes all (cached) settings or other content for that user:
Accountt based settings (and maybe others; e. g. tab setup), drafts.

This is however not what I would expect from a "logout". On every webpage a logout does nothing except log you out (invalidate session). After a re-login everything / every content is restored.

Last changes here with #2579 (security improvements)

(Technically: this is LogoutUsecase#logout)

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
I'd rather rename the action to make clear it destroys data.

Websites can restore data because they save it on their server, but we don't have servers and the Mastodon api does not support storing arbitrary settings. If we keep the data locally we clutter the device (maybe a user logs out to save data?), and restoring only works locally.

**Comment by Lakoja** [comment]
All of these is stored locally (?). I would just need to be reused.
At the moment it is actively deleted in database and shared settings on logout.

**Comment by Lakoja** [comment]
What I notice: The "delete all locally and logout" would then probably need to be put somewhere (profile settings probably).

**Comment by nikclayton** [comment]
https://tech.lgbt/@taminaminam/110684446338006251 is a user report where logging out destroyed all their drafts with no warning.
