### ISSUE TITLE
Dark Theme, text seems to disappear when selected

### ISSUE THREAD

**Issue by mbx96** [tuskyapp/Tusky#3491]
When adding text to a picture text disappears when text is selected and copy - dialog opens

* * * *
- Tusky Version: Tusky Test 21.0-test-9e66ccf4
- Android Version: 13 & 9
- Android Device: Samsung Galaxy s22u & s8
- Mastodon instance (if applicable): Troet.cafe 

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Lakoja** [comment]
Can you post a screenshot?

**Comment by mbx96** [comment]
![Screenshot_20230328_133213_Tusky Test](https://user-images.githubusercontent.com/129048800/228223413-83d266f3-3594-48b5-81b8-78cf705d9712.jpg)

**Comment by Lakoja** [comment]
> Screenshot

Thank's.
What happens if you tap on the three dots?
Can you check this in the lists screen?
(So left swipe on the Tusky home screen > Lists > Add new list - in the text field for the name make a long press to show this selection popup)

**Comment by Lakoja** [comment]
(copying result from the chat as it went undiscussed there)

(Technical)
The reason here seems to be a combination of Tusky and the usage of AlertDialog(Builder):
When using the (system) popup on a text field in such a dialog there is mostly the possibility to see a second popup with menu items that do no fit in the first (...). The first dialog however erroneously leaves room for the second one (and is thus much too big) when normally these two are independent from each other.

This works for all (Tusky) dialogs not using AlertDialog.

I didn't find out yet what makes Tusky behave like this (and other apps not).
