### ISSUE TITLE
UnifiedPush not working on tusky 22

### ISSUE THREAD

**Issue by samuraikid0** [tuskyapp/Tusky#3591]
Running lineageOs with Up-Example app I'm able to receive the test notification, on tusky I don't receive any notification 

By the way Im running 0 google services

Any clue or it's tusky broken ? 

Thanks !

* * * *
- Tusky Version: 22 beta, 21 
- Android Version: 13
- Android Device: samsung

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by SteveDinn** [comment]
Not sure if this is an issue or not, but each time I reboot my phone, I get a new entry in the UP-FCM app.

![Screenshot_20230429-220920](https://user-images.githubusercontent.com/3911507/235330835-7f045bb2-0f8c-4ad6-aa05-14948cc6caee.png)

**Comment by samuraikid0** [comment]
> Not sure if this is an issue or not, but each time I reboot my phone, I get a new entry in the UP-FCM app.
> 
> ![Screenshot_20230429-220920](https://user-images.githubusercontent.com/3911507/235330835-7f045bb2-0f8c-4ad6-aa05-14948cc6caee.png)

Im using nextpush not UP-FCM, sorry for not mention it

**Comment by Lakoja** [comment]
(Slightly?) related #3468

**Comment by Lakoja** [comment]
@SteveDinn Does this really happen on every reboot? I have also three entries there but that is because I have three accounts configured in Tusky.

@samuraikid0 Did you "change" something to do with unified push lately (weeks/months)?
I have been looking in the code and see one problem: One cannot change the provider (distributor) at the moment. Tusky cannot recognize that and the server then happily tries to use a wrong url (the endpoint of the old one).

If you want to you can try to wipe all Tusky data and/or uninstall completely.
(Which will also delete everything else local: e. g. drafts, login, tab configuration)

**Comment by samuraikid0** [comment]
> @SteveDinn Does this really happen on every reboot? I have also three entries there but that is because I have three accounts configured in Tusky.
> 
> @samuraikid0 Did you "change" something to do with unified push lately (weeks/months)? I have been looking in the code and see one problem: One cannot change the provider (distributor) at the moment. Tusky cannot recognize that and the server then happily tries to use a wrong url (the endpoint of the old one).
> 
> If you want to you can try to wipe all Tusky data and/or uninstall completely. (Which will also delete everything else local: e. g. drafts, login, tab configuration)

All the above 

Jami notifications via nextpush work, Up-Example test app sends the notification test 

Tusky doesn't send any notification at all

**Comment by SteveDinn** [comment]
> @SteveDinn Does this really happen on every reboot? I have also three entries there but that is because I have three accounts configured in Tusky

That is entirely possible. I also have 3 accounts, but I also rebooted 3 times. It's more likely that it's due to the accounts, but I didn't think of that! :)

**Comment by samuraikid0** [comment]
solved
