### ISSUE TITLE
Translate context menu only shares first word with external program.

### ISSUE THREAD

**Issue by 0b1kn00b** [tuskyapp/Tusky#3617]
As per title, only one word makes it through to either Google translate or the Google app. This is sometime since November because at one time it was alright.

* * * *
- Tusky Version: 21.0
- Android Version: 12
- Android Device: poco f2 pro
- Mastodon instance (if applicable):

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
How do I get a translate context menu? I don't have it on my device.

**Comment by Lakoja** [comment]
In (for example) the thread view you can long-tap in the text.
This marks the word beneath my finger and pops up a (system) text field popup.
I can either translate this word or select everything and then select translate.
The latter one however correctly transfers all text.

**Comment by 0b1kn00b** [comment]
I have an IPlay 40 pro, which is android 11 and doesn't have the translate item in the menu despite having more or less the same raft of programs. I can't help you further than that.

**Comment by 0b1kn00b** [comment]
In order to trigger the behaviour, you must manually select the text, but not all of it.

try, say

https://friendicarg.nsupdate.info/display/69172192-2064-546a-b5c7-9dc683471819

**Comment by nikclayton** [comment]
Sorry, I still don't understand the difference between what you're experiencing, and what you expect to happen. Please can you provide screenshots showing the issue. Thanks.

**Comment by 0b1kn00b** [comment]
![Screenshot_2023-05-05-13-49-49-400_com.keylesspalace.tusky.jpg](https://user-images.githubusercontent.com/114186/236450471-fd9c4fad-aed9-4126-8f9b-880bca6a789a.jpg)

![Screenshot_2023-05-05-13-49-53-718_com.google.android.apps.translate.jpg](https://user-images.githubusercontent.com/114186/236450495-1fa77b4c-9bd8-40fe-ab48-ad092c5c7b3e.jpg)

To add to the fun, it doesn't *always* do it

**Comment by nikclayton** [comment]
I can't reproduce that.

Here's what it looks like after I've selected some text on the same post:

<img src="https://user-images.githubusercontent.com/773100/236688296-8536004b-6e72-4e18-adce-d96ebc2b47f0.png" width="45%">

And here's what happens after I tap "Translate" on the menu.

<img src="https://user-images.githubusercontent.com/773100/236688330-7a51c061-3a27-42c3-94c6-6c0f2309f734.png" width="45%">

As you can see, it's all translated correctly.

This functionality is provided by Android, not Tusky, so I think this may be an issue with your device.

What happens if you:

1. Select some text from a post
2. Copy that text
3. Paste that text in to a different application (e.g, GMail)
4. Select the pasted text again in the different application
5. Choose the "Translate" option from the "text-selected" menu

?

**Comment by 0b1kn00b** [comment]
You're right, it's somewhere else. Thanks for bearing with me.
