### ISSUE TITLE
Tusky does not show all followers on an account

### ISSUE THREAD

**Issue by ItsRogueRen** [tuskyapp/Tusky#3804]
For some reason, Tusky is missing follower on the list of people an account follows. If I show the list for an account with hundreds of followers, only local accounts are show rather than the entire list. Is there a way to change that?

**Comment by connyduck** [comment]
No, there is no way to change that. Due to the way federation works your instance only knows the local followers and Tusky can only show what your instance knows. This is why there is a "Information below may reflect the user's profile incompletely" text on profiles. You can click it and it will open the website the profile is hosted on and usually more information is available from there.
