### ISSUE TITLE
Instance-specific Character Limit.

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [tuskyapp/Tusky#393]
I'm on a Mastodon instance that offers a 750 characters-limit, but on Tusky I can only post toots 500 characters long. When I was using Mastalab, it counted characters from 0, not from 500 like Tusky and Twidere. Maybe that's one way of giving Tusky an instance-specific character limit? I don't know. But Tusky's limitation definitely defeats the purpose of joining an instance that offers more characters. Please look into this.

**Comment by charlag** [comment]
@iknownothingaboutcomputers I've looked it up and I honestly didn't find any API for getting character limit. There probably should be some but until then I think we cannot do anything about it, sorry.

**Comment by Vavassor** [comment]
It's true there isn't an API call for character limit. It would be possible just to not limit the message on the client side and just let the server respond with whatever 4xx HTTP response code when the messages is too long.

But then you have to wait for the whole message to send including all media to upload in order to even be able to report that the character limit was exceeded, which is a little frustrating.

Also, you wouldn't be able to have an onscreen-character indicator that shows how many characters are left. And, "-4" when you're 4 characters over the limit. It could be changed to count up from zero instead, to show how many characters you've used, I guess? But it's less useful and requires the user to know their instance's character limit.

**Comment by Vavassor** [comment]
Oh, there's also a request for a server constant API issue in mastodon proper tootsuite/mastodon#4915 worth pitching into.

**Comment by charlag** [comment]
Or... It could be set in the app settings. Much easier.

**Comment by connyduck** [comment]
There is another discussion about an character limit API over at https://github.com/tootsuite/mastodon/pull/5697 
I would not give users the possibility to set the limit in Tusky themselves. A wrongly set limit could cause errors and users would blame the developers.

**Comment by lambadalambda** [comment]
It's merged into the glitch.social code (see https://dev.glitch.social/api/v1/instance) and we also have it in pleroma now (https://pleroma.soykaf.com/api/v1/instance), so it would already make sense using this information if it's there, I think.

**Comment by lambadalambda** [comment]
bumping this once more. you think we could get this, @connyduck ?

**Comment by charlag** [comment]
We don't have too many resources rn but if someone could dive in and implement this request I think it would do not too much harm to add it?
It's pretty easy, just 
1. Add needed request in `MastodonAPI`
2. Add length field in `ComposeActivity`
3. Make request in `ComposeActivity` using `mastodonApi` instance
4. Change field in `ComposeActivity`

**Comment by charlag** [comment]
We don't have too many resources rn but if someone could dive in and implement this request I think it would do not too much harm to add it?
It's pretty easy, just 
1. Add needed request in `MastodonAPI`
2. Add length field in `ComposeActivity`
3. Make request in `ComposeActivity` using `mastodonApi` instance
4. Change field in `ComposeActivity`
It's not perfect, but it would work
