### ISSUE TITLE
Why did you make it harder to clear notifications?

### ISSUE THREAD

**Issue by jikamens** [tuskyapp/Tusky#3980]
I considered it a feature, not a bug, that the ability to clear notifications was displayed prominently in Tusky as a button. I clear my notifications regularly, and it's too hard to do in the web app.

Now you've gone and hidden it in a menu and there doesn't appear to be a preference setting to bring back the button. Not a positive change.

* * * *
- Tusky Version: Tusky Test
- Android Version: 14
- Android Device: Pixel 6

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jikamens** [comment]
The very explicit confirmation pop-up that the user had to click ok on wasn't good enough?

My workflow that I understand and prefer has to be slowed down because other people don't read? *sigh*

Is the problem that people were tapping the button by accident, or that "clear" was an ambiguous label?

Maybe you could keep the button but change the label to "delete", just like you made the menu command say "delete" instead of "clear".

Regarding "the needs of the many" you have no idea how many people preferred the old behavior because none of them would ever have any reason to file a report about it.

In any case I do honestly appreciate that you're making an effort to be responsive to feedback, and the fact that I don't agree with this particular change doesn't alter that. So thank you for that.

**Comment by nikclayton** [comment]
> The very explicit confirmation pop-up that the user had to click ok on wasn't good enough?

Yes. Honestly, I was surprised too. I think sometimes people are just conditioned to click through dialogs without checking that it's saying what they expect.

> Regarding "the needs of the many" you have no idea how many people preferred the old behavior because none of them would ever have any reason to file a report about it.

That's correct, Tusky doesn't have any sort of analytics that would say, e.g., how many people actually use this function, how many people tapped "Clear" and then went back instead of confirming on the dialog, and so on.

There are ways to do that in a privacy preserving way. But I don't know of any ways of doing that will convince anyone who doesn't want to be convinced that this isn't the thin edge of the wedge, and that Tusky is going to start collecting and selling your private data. So we don't do it.

So it's difficult to make a data driven decision about changes like this. The best we can do is monitor issues like this, and see if there's feedback from other Tusky Nightly users either here, or to the Mastodon account. And then make a judgement call.

**Comment by mcclure** [comment]
Hi, we'll be at least reconsidering this.

**Comment by mcclure** [comment]
@jikamens , we'll be reconsidering this.

**Comment by connyduck** [comment]
this feature was added back in Tusky 24
