### ISSUE TITLE
"nothing here" when there's something there

### ISSUE THREAD

**Issue by JVimes** [tuskyapp/Tusky#4047]
The post list on [this account](https://dice.camp/@qenen)  shows "nothing here" in Tusky, but has posts on web. 

* * * *
- Tusky Version: 23.0
- Android Version: 13
- Android Device: Pixel 4a
- Mastodon instance (if applicable): dice.camp

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
If you see the message "Information below may reflect the user's profile incompletely. Press to open full profile in browser." on the profile, that is not a bug but correct behavior.
It happens because you are viewing a profile on a different server and no posts from that server have federated to your server.

**Comment by JVimes** [comment]
I missed that, thank you. It's easy to miss.
