### ISSUE TITLE
[friendica] Post length limited to 500 in recent Friendica RC

### ISSUE THREAD

**Issue by kr428** [tuskyapp/Tusky#4100]
Using Tusky Test 23.0-e9195846 with Friendica 2023.09-rc on loma.ml, I noticed that all of a sudden I can't compose posts longer than 500 chars anymore. Current Tusky stable does however display the "correct" amount of chars allowed per post (around 20k on that instance). Any way to fix this?

**Comment by Tak** [comment]
My instinct is that it's a regression caused by [instance v2 support](https://github.com/tuskyapp/Tusky/pull/4062), in particular I notice that https://loma.ml/api/v2/instance fails to return a number of fields in `configuration` that I understood to be "mandatory" from the mastodon api docs

I'll investigate

**Comment by kr428** [comment]
Fixed, thanks.
