### ISSUE TITLE
Multiple accounts bug: boosts from one account's home timeline appear in another's

### ISSUE THREAD

**Issue by nehemiagurl** [tuskyapp/Tusky#4402]
### Detailed description

I have multiple accounts connected to Tusky.
Account 1 follows maloki. Account 2 does not.
multiple boosts from maloki appeared today in Account 2's home timeline.
![Screenshot_20240428-213752_Tusky](https://github.com/tuskyapp/Tusky/assets/109424320/5023f3dc-d920-4566-81e4-126f69a7d6fa)
trying to view the post or the boosting account results in an error:
![Screenshot_20240428-212743_Tusky](https://github.com/tuskyapp/Tusky/assets/109424320/24a513cc-6903-424c-a4a2-92fb89da1d95)
![Screenshot_20240428-213803_Tusky](https://github.com/tuskyapp/Tusky/assets/109424320/c27ffdd2-240b-41a4-aa7e-038bc0679af9)

### Steps to reproduce the problem

1. Connect Tusky to multiple accounts
2. Have Account 1 follow Some User.
3. Browse the home timeline of Account 2
4. boosts from Some Account appear in Account 2's timeline

### Debug information

Tusky 25.0 beta 1

Device:

samsung SM-A125F
Android version: 12
SDK version: 31

Account:

@yuvalne@tooot.im
Version: 4.2.8

**Comment by nehemiagurl** [comment]
Right after writing this report, I got this bug with another user, this time with a regular post, non-boost. trying to view the posting account results in the same error.

**Comment by connyduck** [comment]
Do you remember what you did before this happened? Are those posts that are shown on the wrong account from the top of the right accounts timeline, or from randomly in between? How many posts are multiple? 1-2 or more like 10-20 or even more?

**Comment by nehemiagurl** [comment]
no need to do anything in particular for this to happen - this occurs even after switching to Account 1 and back, or after closing the app and reopnening.
the posts are in random bursts in bewteen. there's 60-something posts from the correct account counting from the newest point of the timeline, then four wrong posts. then ten correct posts, then seven wrong ones.
they also appear consistently at the same point of the timeline. maybe that means only the newest posts in the timeline were refreshed and everything else stayed the same, I don't know.

**Comment by nehemiagurl** [comment]
I'm not sure if and how to fully reload the home timeline, even if I force stop the app the wrong posts are in exactly the same place, idk if Tusky does some caching but if it does that's probably why

**Comment by connyduck** [comment]
Yes there is a cache, to remove it you will have to log out & login again for all affected accounts. 
Once the posts are in the wrong timeline they will stay there.
The question is how do they end up there in the first place 🤔

**Comment by nehemiagurl** [comment]
then assuming all wrong posts were fetched at the same time, it will be quite hard to pinpoint the action that happened right before it. the first wrong posts are from 11 hours ago and they appear in the correct spot in the timeline (i.e. above posts that are 12 hours old but below ones that are 10 hours old). I also switched to Account 2 multiple times throughout the day, but I only scrolled down enough to see the wrong posts for the first time right before filing this report.

**Comment by kouya** [comment]
I am having the (maybe) similar issue. Here is what I observed:

I've newly installed 25.1 from f-droid
Added 7 accounts to it (5 bots posting foxes, don't judge me!)
Then some weird issue occurred.

My main account would have 30 older posts (all were 1d old, collection of boosts and posts) on top that never moved. New posts would appear below them.
I logged out of it and back in, which fixed it on that account.
But then those 30 posts suddenly appeared on another account where they shouldn't be. Just as described above. This repeats if I log out of the "newly broken account".

I didn't really find a pattern, other than that the posts are always the same if they end up on another account and will stay on top. I originally used "log in with browser", which is firefox, because only that had the passwords saved and I was too lazy.

Cleared the cache on the settings but didn't change anything.

Logged out of all accounts and readded them via "log in with tusky" but the same posts reappeared on one of the accounts. Was neither the first one added, nor the last. Actually it was specifically the 4th added but that's probably just random coincidence.

Not sure if any of that helps, but maybe some behaviour there will point to something. :3

**Comment by nehemiagurl** [comment]
just happened again on the same two accounts (and in the same direction, so from Account 1 to Account 2 like before) on version 25.2 stable.
this time the posts are >2 days old so way harder to figure out what might have been the trigger.

**Comment by nehemiagurl** [comment]
okay, happened again, this time with some specificity that may help:
I switched from Account 1 to Account 2. Account 2's feed loaded not at the top of the feed, but right below the first "Load more". The 7 posts following that "load more" were all from the feed of Account 1, dated to around 13 hours ago.
Curiously enough, 13 hours ago I was asleep, so whatever caused this likely didn't happen as those were posted, but somewhat later than that.
Two not-so-common things to happen today were:
1. a notification for a report on Account 2, though this also happened a few days ago with the bug not happening again after those.
2. an from Tusky of a post created from Web on account 1.

maybe it's neither of those, but I really can't think of anything else.

**Comment by nehemiagurl** [comment]
aha! I think I found the trigger!
I got a notification for [this post](https://433.world/@swordsoprano/112768600382212736) while being on account 2. after clicking on the notification, opening the post, reacting and going back to the home feed, the very first post I see is a post from account 2, right after the "load more".
![Screenshot_20240711-190021_Tusky](https://github.com/tuskyapp/Tusky/assets/109424320/2d22d67e-0a63-4dd7-a11d-da75f0bd48ed)
it could be that the very act of switching accounts not via the top bar is at fault.

**Comment by Tak** [comment]
Aha, that's something to look into, good find!

**Comment by Packbat** [comment]
I think I might have stumbled over a hypothesis, because I just encountered the bug myself for the first time.

Is it possible that, under some circumstances:

- you begin requesting posts for a column
- you switch accounts before the request resolves, and then
- the new posts are populated into the column for the other account?

One of my instances has been having a lot of performance issues, and normally I wait for the columns to finish loading before switching, but today I didn't and, sure enough, I had posts for the wrong account.

**Comment by Packbat** [comment]
I think I might have stumbled over a hypothesis, because I just encountered the bug myself for the first time.

Is it possible that, under some circumstances:

- you begin requesting posts for a column
- you switch accounts before the request resolves, and then
- the new posts are populated into the column for the other account?

One of my instances has been having a lot of performance issues, and normally I wait for the columns to finish loading before switching, but today I didn't and, sure enough, I had posts for the wrong account.

edit: Tusky 26.0

samsung SM-A146U
Android version: 14
SDK version: 34

**Comment by charlag** [comment]
hey, there's a fix on the way (we hope). thanks for all the info though!

**Comment by Packbat** [comment]
oh heck yeah!

(in case fix doesn't fix, more info: I think possibly I was requesting new posts on *both instances* at the same time - requested new posts, got bored, swapped instances, requested new posts.)
