### ISSUE TITLE
[Feature Request]: Recalculate toots relative timestamp on pull-to-refresh

### ISSUE THREAD

**Issue by MasterGroosha** [tuskyapp/Tusky#452]
When you pull-to-refresh any timeline, relative timestamp mark (as seen on screenshot below) isn't recalculated relatively to the current time. It does update on switching back and forth between different timelines though.

![timestamp in toot view](https://user-images.githubusercontent.com/2780044/32713651-440cc4f6-c85b-11e7-935a-10708090e2c4.png)

Using Tusky 1.3.1.

**Comment by charlag** [comment]
We could do better than refreshing on pull, I think we should automatically change it with time.
Something like this may work:
https://stackoverflow.com/a/14512130/1923879
I'm not sure if broadcastReceiver is cheap or not and if it worths putting in a holder. If it's not we'd better notify adapter.

**Comment by MasterGroosha** [comment]
So time will be recalculated in real-time for each new item from ListView appearing on screen? Won't it cause any kind of freezes on low-end devices?

**Comment by charlag** [comment]
This thing does this only every minute.
It will only recalculate it for views currently visible (and probably in the nearby timeline as well).
I've also found some libraries
https://github.com/damien5314/TimeSinceTextView

https://github.com/curioustechizen/android-ago

**Comment by connyduck** [comment]
Yes, we could do better (and we should) but I think a quck fix that calls `notifyDataSetChanged();` on every refresh would also be ok for now.

**Comment by charlag** [comment]
This leaves us with other problems. First, it may be quite expensive but it shouldn't be too bad. Second, we may loose things like position in the timeline (but since we're in the top on refresh it shouldn't be that bad). This can and should be solved by utilizing stable IDs. The thing is that we need mapping from ```String``` IDs to ```long```s. Maybe we could keep a map or something. Pinterest released a framework for RecyclerView recently which does some of that bookkeeping, maybe we should check how they do it.
I would love to just do ```notfiyDatasetHasChanged()``` because it would let us get rid of some ugly logic (and move loading from the Fragments)

**Comment by charlag** [comment]
It's implemented with #1130 / #1113 I believe
