### ISSUE TITLE
Improve media cache support

### ISSUE THREAD

**Issue by Angristan** [tuskyapp/Tusky#658]
Right now Tusky consumes a lot of data because it constantly downloads media from the server.

It would be very... Earth-friendly to add cache for:

- profile pictures
- banners
- media attachements 
- custom emojis

**Comment by charlag** [comment]
Hi, thanks for reporting!
Yes, this was nagging me a lot but it's not too easy.
Of course we cache things now, both on disk and in memory. The problem is that cache is shared between all network request and cache is cleared as "first in, first out". I've tried to increase cache size to 100 Mb or so but it didn't change much. We need some way to affect caching priority but I did not see any way to do this yet.

**Comment by charlag** [comment]
I definitely want to solve this but we have a lot of things to fix too so please, give us some time.

**Comment by connyduck** [comment]
Tusky already has a cache for images, but it is currently limited to 10mb. I will improve it so it adapts to available storage.

**Comment by charlag** [comment]
@connyduck I think system already takes care of this? Cache is stored in the cache folder which is cleared by the system in case it needs storage. User doesn't have much control tho.

**Comment by connyduck** [comment]
@charlag we could try not caching fullsize media on disk at all? It takes the most space and I think it is quite a rare usecase where users view media, then close the app so it gets thrown out of memory cache and then view it again

**Comment by charlag** [comment]
@connyduck yes, I was proposing that as well. I think tons of small requests eat up space too but doing this thing with full-size media is definetely an improvement.
Now question: can we tell it to Picasso? There's a cache policy, need to check it

**Comment by charlag** [comment]
Yes, `NetworkPolicy.NO_STORE` is what we need
