### ISSUE TITLE
Direkt message column

### ISSUE THREAD

**Issue by mal0ki** [tuskyapp/Tusky#832]
Since it's a request by both myself and other users, I'm adding an issue for it for someone to pick up if they feel like it. 

On Mastodon web interface you can view your Direct Messages in it's own column. 
It would be beneficial to some users to be able to do this on Tusky too.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment]
Good idea!
I think this change should be incorporated into a bigger concept that allows customization of all tabs and also adds image, hashtag and list tabs.

**Comment by mal0ki** [comment]
I like that, let's talk about it on Monday!

**Comment by connyduck** [comment]
Ok, since Mastodon 2.6 removed direct messages from timelines this got a lot more priority

**Comment by koyuawsmbrtn** [comment]
I really like the approach I mentioned earlier to do it like Mast (iOS) does it, but a little bit different. Using a bolt icon instead of a bell icon and having two different sub-views for either notifications (default, bell icon) or direct messages (envelope icon). I have no idea on how to match it with the current UI so I think some thinking work must be done on this.

**Comment by connyduck** [comment]
closed by #1012
