### ISSUE TITLE
Tusky freeze when opening picture if your network is not responding

### ISSUE THREAD

**Issue by a1batross** [tuskyapp/Tusky#968]
I was in metro, when tried to open random picture from wxw.moe and using cellular network, where Android may report LTE is active, but in reality network doesn't work.

Tusky was freezed in home activity, so it even don't reported that image is loading currently and image viewer activity don't created yet.

However, Android doesn't recognized this as ANR.

* * * *
- Tusky Version: 4.1
- Android Version: 8.1
- Android Device: Xiaomi Redmi Note 4
- Mastodon instance (if applicable): niu.moe(local), wxw.moe

- Yes, I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Dostoi** [comment]
I'm having an issue similar to this one. I noticed the tusky wait for all available thumbnail to be loaded before opening and loading the picture you're trying to load.
A good way to test it is to use orbot on a low network and go to someone media page and try to open a picture before all thumbnail are loaded.

**Comment by averageunicorn** [comment]
An addition: As I experienced it, Tusky doesn't freeze completely, but you have to press back before you can do anything again.

**Comment by charlag** [comment]
Happens to me on a slow network when I 
1) try to open it
2) Don't wait until it loads and press back
3) Try to open it again. Visually nothing changes but it's unresponsive until you press back

My theory is that it's happening because our image loading library (Picasso) says that it has a cached version so we try to play an animation after loading because it should be super fast but it actually isn't. Maybe it will go away when we update Picasso.

Another option is that it's some state/timing issue.

**Comment by connyduck** [comment]
fixed by #1175
